'use strict';
const { buildOverpassQuery, parseOverpass, mapGooglePlace, sanitizeKeywords } = require('./opportunity');
const USER_AGENT = 'DraftWA-MapSearch/1.0 (+https://draftwa-mobile-five.vercel.app/map/)';
const OVERPASS = ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const ALLOWED_ORIGINS = new Set([
  'https://draftwa-map-search.vercel.app',
  'https://draftwa-mobile-five.vercel.app',
  'https://draftwa-mobile-elia-btks-projects.vercel.app'
]);
function timeout(ms){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return{signal:c.signal,done:()=>clearTimeout(t)}}
async function fetchJson(url,opt={},ms=15000){const t=timeout(ms);try{const r=await fetch(url,{...opt,signal:t.signal}),txt=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${txt.slice(0,180)}`);return JSON.parse(txt)}finally{t.done()}}
async function collectOsm(center,radiusM,categories){const query=buildOverpassQuery(center.lat,center.lng,radiusM,categories);let last;for(const endpoint of OVERPASS){try{const data=await fetchJson(endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8','accept':'application/json','user-agent':USER_AGENT},body:new URLSearchParams({data:query}).toString()},35000);return{endpoint,entities:parseOverpass(data,center),rawCount:Array.isArray(data.elements)?data.elements.length:0}}catch(e){last=e}}throw last||new Error('Overpass indisponible')}
async function collectGoogle(center,radiusM,keywords,apiKey){if(!apiKey)return{enabled:false,entities:[],queries:0,errors:[]};const qs=sanitizeKeywords(keywords,6),queries=qs.length?qs:['companies','technology','industry','bank'],entities=[],errors=[];for(const textQuery of queries.slice(0,6)){try{const data=await fetchJson('https://places.googleapis.com/v1/places:searchText',{method:'POST',headers:{'content-type':'application/json','X-Goog-Api-Key':apiKey,'X-Goog-FieldMask':'places.id,places.displayName,places.formattedAddress,places.location,places.types,places.primaryType,places.websiteUri,places.nationalPhoneNumber,places.internationalPhoneNumber,places.googleMapsUri,places.rating,places.userRatingCount'},body:JSON.stringify({textQuery,pageSize:20,rankPreference:'RELEVANCE',locationBias:{circle:{center:{latitude:center.lat,longitude:center.lng},radius:Math.min(radiusM,50000)}}})},18000);for(const p of data.places||[]){const m=mapGooglePlace(p,center);if(m&&m.distanceFromCenterM<=radiusM*1.1)entities.push(m)}}catch(e){errors.push(`${textQuery}: ${e.message}`)}}return{enabled:true,entities,queries:queries.length,errors}}
async function geocode(q){q=String(q||'').trim();if(q.length<2||q.length>180)throw new Error('Recherche de lieu invalide');const u=new URL('https://nominatim.openstreetmap.org/search');u.searchParams.set('q',q);u.searchParams.set('format','jsonv2');u.searchParams.set('limit','8');u.searchParams.set('addressdetails','1');const data=await fetchJson(u.toString(),{headers:{accept:'application/json','accept-language':'fr,en;q=.8,de;q=.7','user-agent':USER_AGENT}},12000);return(Array.isArray(data)?data:[]).map(x=>({displayName:x.display_name||'',lat:Number(x.lat),lng:Number(x.lon),type:x.type||'',category:x.category||'',boundingBox:x.boundingbox||null})).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng))}
async function boundary(q){q=String(q||'').trim();if(q.length<2||q.length>180)throw new Error('Recherche de frontière invalide');const u=new URL('https://nominatim.openstreetmap.org/search');u.searchParams.set('q',q);u.searchParams.set('format','jsonv2');u.searchParams.set('limit','1');u.searchParams.set('polygon_geojson','1');u.searchParams.set('addressdetails','1');const data=await fetchJson(u.toString(),{headers:{accept:'application/json','accept-language':'fr,en;q=.8','user-agent':USER_AGENT}},15000);const item=Array.isArray(data)&&data[0];if(!item) return null;return{displayName:item.display_name||q,lat:Number(item.lat),lng:Number(item.lon),boundingBox:item.boundingbox||null,geojson:item.geojson||null,type:item.type||'',category:item.category||''}}
function corsHeaders(req){const origin=req&&req.headers&&req.headers.origin;const out={'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type, Accept','access-control-max-age':'86400','vary':'Origin'};if(origin&&ALLOWED_ORIGINS.has(origin))out['access-control-allow-origin']=origin;return out}
function headers(extra={},req=null){return{'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin',...corsHeaders(req),...extra}}
function applyHeaders(res,req,extra={}){for(const[k,v]of Object.entries(headers(extra,req)))res.setHeader(k,v)}
function json(res,status,body,extra={},req=null){res.statusCode=status;applyHeaders(res,req,{'content-type':'application/json; charset=utf-8',...extra});res.end(JSON.stringify(body))}
function options(req,res){if(req.method!=='OPTIONS')return false;res.statusCode=204;applyHeaders(res,req);res.end();return true}
async function body(req,max=1024*1024){if(req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;let raw='';for await(const ch of req){raw+=ch.toString('utf8');if(Buffer.byteLength(raw)>max)throw new Error('Requête trop volumineuse')}return raw.trim()?JSON.parse(raw):{}}
module.exports={collectOsm,collectGoogle,geocode,boundary,json,headers,baseHeaders:headers,applyHeaders,options,body,readJsonBody:body};
