from pathlib import Path
import re, sys, json
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name, cond):
    checks.append((name,bool(cond)))
    print(('PASS' if cond else 'FAIL'), name)
manifest=(ROOT/'app/src/main/AndroidManifest.xml').read_text()
service=(ROOT/'app/src/main/java/com/draftwa/mobile/DraftAccessibilityService.java').read_text()
update=(ROOT/'app/src/main/java/com/draftwa/mobile/UpdateManager.java').read_text()
prefs=(ROOT/'app/src/main/java/com/draftwa/mobile/Prefs.java').read_text()
config=(ROOT/'app/src/main/res/xml/accessibility_service_config.xml').read_text()
check('INTERNET permission', 'android.permission.INTERNET' in manifest)
check('REQUEST_INSTALL_PACKAGES permission', 'android.permission.REQUEST_INSTALL_PACKAGES' in manifest)
check('Accessibility reports view IDs', 'flagReportViewIds' in config)
for i in ['draft_indicator','conversation_list','entry','send']:
    check('WhatsApp ID '+i, '"'+i+'"' in service)
check('Fail safe pauses on set text failure', 'SET_TEXT_VERIFY_FAILED' in service and 'putBoolean(Prefs.RUNNING, false)' in service)
check('Diagnostic skips send', 'SEND_SKIPPED_DIAGNOSTIC' in service)
check('Exact filter matching', 'findExactTextClickableOutside' in service)
check('Draft filter labels excluded from fallback', 'all.equals("drafts") || all.equals("brouillons")' in service)
check('All/Toutes fallback selection', 'ALL_FILTER_CLICK' in service and '"Toutes", "All"' in service)
check('Generic scrollable list fallback', 'findBestScrollable' in service)
check('Viewport loop guard', 'viewportSignature' in service and 'DRAFT_SCAN_STOP_SAME_VIEWPORT' in service)
check('Scan page logging', 'DRAFT_SCAN_PAGE' in service)
check('Diagnostic preview is non destructive', 'TRANSFORM_PREVIEW' in service and 'Strictly non-destructive' in service)
check('Diagnostic never uses temporary set text', 'DIAG_TRANSFORM' not in service and 'DIAG_RESTORE' not in service)
check('Diagnostic does not delete rejected drafts', 'DRAFT_DELETE_SKIPPED_DIAGNOSTIC' in service)
check('SHA validation', 'SHA-256 invalide' in update)
check('Package validation', 'Package inattendu' in update)
check('Signature validation', 'Signature release différente' in update)
check('Version validation', 'Version non supérieure' in update)
check('PackageInstaller used', 'PackageInstaller.SessionParams' in update)
check('Manifest requires HTTPS', 'Manifeste non HTTPS' in update)
check('Update APK requires HTTPS', 'URL APK non HTTPS' in update)
check('Update size capped', 'APK de mise à jour trop volumineuse' in update)
check('Install permission resumes update', 'PENDING_INSTALL_PERMISSION' in update and 'PENDING_INSTALL_PERMISSION' in (ROOT/'app/src/main/java/com/draftwa/mobile/MainActivity.java').read_text())
check('Default Soko', '"Soko"' in prefs)
check('Default removal', '",Enregistré,"' in prefs)
check('Pause resume persistence', 'PAUSED' in prefs and 'BATCH_TARGET' in prefs)
check('Auto update default true', 'AUTO_UPDATE)) e.putBoolean(AUTO_UPDATE, true)' in prefs)
check('Auto download default true', 'AUTO_DOWNLOAD)) e.putBoolean(AUTO_DOWNLOAD, true)' in prefs)
failed=[n for n,v in checks if not v]
print(json.dumps({'total':len(checks),'passed':len(checks)-len(failed),'failed':failed},ensure_ascii=False))
sys.exit(1 if failed else 0)
