from pathlib import Path
import re, sys, json
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name, cond):
    checks.append((name,bool(cond)))
    print(('PASS' if cond else 'FAIL'), name)
manifest=(ROOT/'app/src/main/AndroidManifest.xml').read_text()
service=(ROOT/'app/src/main/java/com/draftwa/mobile/DraftAccessibilityService.java').read_text()
update=(ROOT/'app/src/main/java/com/draftwa/mobile/UpdateManager.java').read_text()
prefs=(ROOT/'app/src/main/java/com/draftwa/mobile/Prefs.java').read_text()
main=(ROOT/'app/src/main/java/com/draftwa/mobile/MainActivity.java').read_text()
diag=(ROOT/'app/src/main/java/com/draftwa/mobile/DiagnosticLog.java').read_text()
opportunity=(ROOT/'app/src/main/java/com/draftwa/mobile/OpportunityActivity.java').read_text()
config=(ROOT/'app/src/main/res/xml/accessibility_service_config.xml').read_text()
build=(ROOT/'app/build.gradle').read_text()
web_index=(ROOT/'opportunity-web/public/opportunities/index.html').read_text()
web_search=(ROOT/'opportunity-web/api/opportunities/search.js').read_text()
web_lib=(ROOT/'opportunity-web/lib/opportunity.js').read_text()

check('INTERNET permission', 'android.permission.INTERNET' in manifest)
check('REQUEST_INSTALL_PACKAGES permission', 'android.permission.REQUEST_INSTALL_PACKAGES' in manifest)
check('Accessibility service bind permission', 'android.permission.BIND_ACCESSIBILITY_SERVICE' in manifest)
check('Accessibility service exported for system binding', 'android:name=".DraftAccessibilityService"' in manifest and 'android:exported="true"' in manifest)
check('WhatsApp Business package visibility', '<package android:name="com.whatsapp.w4b"' in manifest)
check('Accessibility reports view IDs', 'flagReportViewIds' in config)
for i in ['draft_indicator','conversation_list','entry','send']:
    check('WhatsApp ID '+i, '"'+i+'"' in service)
check('Fail safe pauses on set text failure', 'SET_TEXT_VERIFY_FAILED' in service and 'putBoolean(Prefs.RUNNING, false)' in service)
check('Diagnostic skips send', 'SEND_SKIPPED_DIAGNOSTIC' in service)
check('Exact filter matching', 'findExactTextClickableOutside' in service)
check('Draft filter labels excluded from fallback', 'all.equals("drafts") || all.equals("brouillons")' in service)
check('All/Toutes fallback selection', 'ALL_FILTER_FOUND' in service and '"Toutes", "All"' in service)
check('Generic scrollable list fallback', 'findBestScrollable' in service)
check('Viewport end requires repeated confirmation', 'viewportSignature' in service and 'END_STABLE_CONFIRMATIONS' in service and 'DRAFT_SCAN_END_CONFIRMED' in service)
check('Transient list loss retries instead of ending', 'LIST_CONTAINER_MISSING_RETRY' in service and 'DRAFT_LIST_UNAVAILABLE' in service and 'MAX_LIST_MISSING_RETRIES' in service)
check('Gesture scroll fallback exists', 'GestureDescription' in service and 'dispatchListSwipe' in service and 'LIST_SCROLL_GESTURE' in service)
scroll_block = service[service.find('private int performRobustScroll'):service.find('private boolean dispatchListSwipe')]
check('Fresh node scroll retried before gesture fallback', 'ACTION_SCROLL_FORWARD' in scroll_block and 'ACTION_SCROLL_DOWN' in scroll_block and 'dispatchListSwipe' in scroll_block and scroll_block.find('ACTION_SCROLL_FORWARD') < scroll_block.find('dispatchListSwipe'))
check('Gesture acceptance is explicitly unverified', 'mode=gesture-unverified' in service and 'gesture-no-movement-confirmed' in service)
check('Large draft lists have extended scan budget', 'MAX_SCROLLS = 120' in service)
check('Scroll guards persisted and reset', 'SCROLL_STALL_COUNT' in prefs and 'LIST_MISSING_COUNT' in prefs and '.putInt(SCROLL_STALL_COUNT, 0)' in prefs and '.putInt(LIST_MISSING_COUNT, 0)' in prefs)
check('Scan page logging', 'DRAFT_SCAN_PAGE' in service)
check('Diagnostic transform is restored', 'DIAG_TRANSFORM' in service and 'DIAG_RESTORE' in service and 'RESTORED_OK' in service)
check('Diagnostic temporary set text is verified', 'TRANSFORM_PASS' in service and 'DIAGNOSTIC_RESTORE_VERIFY' in service and 'SET_TEXT_VERIFY_FAILED' in service)
check('Diagnostic does not delete rejected drafts', 'DIAGNOSTIC_DELETE_SKIPPED' in service and service.find('if (diagnostic)') < service.find('if ("Détruire".equalsIgnoreCase(reject))'))
check('Return-to-list recovery exists', 'RETURN_TO_LIST_BEGIN' in service and 'RETURN_TO_LIST_CONFIRMED' in service and 'RETURN_TO_LIST_BACK' in service)
check('Start-inside-chat is normalized', 'START_CONTEXT_CHAT' in service and 'currentFingerprint.isEmpty()' in service)
check('Post-send pause waits for navigation recovery', 'returningToList' in service and service.find('if (returningToList)') < service.find('long next = sp.getLong(Prefs.NEXT_ACTION_AT'))
check('SHA validation', 'SHA-256 invalide' in update)
check('Package validation', 'Package inattendu' in update)
check('Signature validation', 'Signature release différente' in update)
check('Version validation', 'Version non supérieure' in update)
check('PackageInstaller used', 'PackageInstaller.SessionParams' in update)
check('Manifest requires HTTPS', 'Manifeste non HTTPS' in update)
check('Update APK requires HTTPS', 'URL APK non HTTPS' in update)
check('Update size capped', 'APK de mise à jour trop volumineuse' in update)
check('Install permission resumes update', 'PENDING_INSTALL_PERMISSION' in update and 'PENDING_INSTALL_PERMISSION' in main)
check('Default Soko', '"Soko"' in prefs)
check('Default removal', '",Enregistré,"' in prefs)
check('Pause resume persistence', 'PAUSED' in prefs and 'BATCH_TARGET' in prefs)
check('Auto update default true', 'AUTO_UPDATE)) e.putBoolean(AUTO_UPDATE, true)' in prefs)
check('Auto download default true', 'AUTO_DOWNLOAD)) e.putBoolean(AUTO_DOWNLOAD, true)' in prefs)
check('Guided diagnostic resumes after accessibility', 'PENDING_DIAGNOSTIC_START' in prefs and 'GUIDED_DIAGNOSTIC_RESUME' in main)
check('Missing WhatsApp blocks run', 'refuseMissingWhatsApp' in main and 'WA_BUSINESS_MISSING' in main and main.find('isWhatsAppBusinessInstalled()') < main.find('Prefs.resetRunState(this)'))
safe_block = diag[diag.find('static synchronized String safeSummary'):diag.find('static synchronized void clear')]
check('Safe diagnostic strips event details', 'safeSummary' in safe_block and 'parts.length >= 2' in safe_block and 'append(parts[1])' in safe_block and 'parts[2]' not in safe_block and 'Événements (détails masqués)' in main)
check('UI version comes from BuildConfig', '"v" + BuildConfig.VERSION_NAME' in main)
check('Release version is 0.8.3', "orElse('803')" in build and "orElse('0.8.3')" in build)

check('Opportunity activity declared', 'android:name=".OpportunityActivity"' in manifest and 'android:exported="false"' in manifest)
check('Opportunity UI entry exists', 'Ouvrir Carte & Prospection' in main and 'OpportunityActivity.class' in main)
check('Opportunity URL is HTTPS build config', 'DRAFTWA_OPPORTUNITY_URL' in build and 'https://draftwa-mobile-five.vercel.app/opportunities/' in build)
check('Opportunity WebView no JS bridge', 'addJavascriptInterface' not in opportunity)
check('Opportunity WebView blocks cleartext', 'MIXED_CONTENT_NEVER_ALLOW' in opportunity and '"https".equalsIgnoreCase' in opportunity)
check('Opportunity WebView restricts DraftWA host', 'draftwa-mobile-five.vercel.app' in opportunity and 'ALLOWED_HOST.equalsIgnoreCase' in opportunity)
check('Opportunity backend uses server search', '/api/opportunities/search' in web_index or '/api/opportunities/search' in (ROOT/'opportunity-web/public/opportunities/app.js').read_text())
check('Opportunity backend has OSM collection', 'collectOsm' in web_search and 'buildOverpassQuery' in web_lib)
check('Opportunity backend has server scoring', 'rankEntities' in web_search and 'scoreEntity' in web_lib)
check('Opportunity search streams progress', 'application/x-ndjson' in web_search and re.search(r"type\s*:\s*['\"]progress['\"]", web_search) is not None)

failed=[n for n,v in checks if not v]
print(json.dumps({'total':len(checks),'passed':len(checks)-len(failed),'failed':failed},ensure_ascii=False))
sys.exit(1 if failed else 0)
